# Generated by Django 5.2.8 on 2025-11-06 04:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guardian",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID público para ser usado em URLs e APIs.",
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email usado para login.", max_length=200, unique=True
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Nome completo do responsável.", max_length=300
                    ),
                ),
                (
                    "agreed_to_terms",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o usuário concordou com os termos de uso.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsável",
                "verbose_name_plural": "Responsáveis",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID público para ser usado em URLs e APIs.",
                        unique=True,
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        help_text="Nome ou apelido do aluno.", max_length=300
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, help_text="Data de Nascimento.", null=True
                    ),
                ),
                (
                    "school_year",
                    models.CharField(
                        choices=[
                            ("ano_1", "1º Ano"),
                            ("ano_2", "2º Ano"),
                            ("ano_3", "3º Ano"),
                            ("ano_4", "4º Ano"),
                            ("ano_5", "5º Ano"),
                            ("ano_6", "6º Ano"),
                            ("ano_7", "7º Ano"),
                            ("ano_8", "8º Ano"),
                            ("ano_9", "9º Ano"),
                        ],
                        help_text="Ano escolar do aluno.",
                        max_length=10,
                    ),
                ),
                (
                    "adhd_type",
                    models.CharField(
                        choices=[
                            ("desatento", "Desatento"),
                            ("hiperativo_impulsivo", "Hiperativo/Impulsivo"),
                            ("combinado", "Combinado"),
                            ("nao_informado", "Não Informado"),
                        ],
                        default="nao_informado",
                        help_text="Tipo de TDAH do aluno.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guardian",
                    models.ForeignKey(
                        help_text="Responsável vinculado a este aluno.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Aluno",
                "verbose_name_plural": "Alunos",
            },
        ),
    ]
