# Generated by Django 5.2.8 on 2025-11-10 19:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='ID público para ser usado em URLs e APIs.', unique=True)),
                ('subject', models.CharField(help_text='Assunto do ticket.', max_length=255)),
                ('message', models.TextField(help_text='Descrição detalhada do problema.')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_andamento', 'Em Andamento'), ('resolvido', 'Resolvido')], default='novo', help_text='Status atual do ticket.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Data em que o ticket foi marcado como resolvido.', null=True)),
                ('user', models.ForeignKey(help_text='Usuário que abriu o chamado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket de Suporte',
                'verbose_name_plural': 'Tickets de Suporte',
                'ordering': ['-created_at'],
            },
        ),
    ]
