# Generated by Django 5.2.8 on 2025-11-10 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='audience',
        ),
        migrations.RemoveField(
            model_name='course',
            name='published_at',
        ),
    ]
