# Generated by Django 5.2.8 on 2025-11-07 00:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='ID público para ser usado em URLs e APIs.', unique=True)),
                ('title', models.CharField(help_text="Título do material (ex: 'Slides da Aula', 'Código Fonte').", max_length=255)),
                ('file_url', models.URLField(help_text='URL para o arquivo (PDF, ZIP, etc).', max_length=255)),
                ('file_type', models.CharField(blank=True, help_text="Tipo do arquivo (ex: 'pdf', 'zip').", max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(help_text='Lição à qual este material pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='learning.lesson')),
            ],
            options={
                'verbose_name': 'Material de Apoio',
                'verbose_name_plural': 'Materiais de Apoio',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='ID público para ser usado em URLs e APIs.', unique=True)),
                ('language_code', models.CharField(help_text="Código da língua (ex: 'pt-BR', 'en-US').", max_length=10)),
                ('file_url', models.URLField(help_text='URL para o arquivo .vtt ou .srt.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(help_text='Lição de vídeo à qual esta legenda pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='learning.lesson')),
            ],
            options={
                'verbose_name': 'Legenda',
                'verbose_name_plural': 'Legendas',
                'ordering': ['language_code'],
                'unique_together': {('lesson', 'language_code')},
            },
        ),
    ]
